# -*- coding: utf-8 -*-
"""exercicios_T11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GK_2bNYtgBrH6dY5wJGy5pCApInsdPcV
"""

# Atividade 1 - Verificador de Velocidade
# Lendo a velocidade
velocidade_do_carro = int(input("Digite  a velocidade do carro (km/h): "))

# Verificando a condicao
if velocidade_do_carro <= 80:
    print("Velocidade permitida. Dirija com segurança!")
else:
    print("Você foi multado")

# Atividade 2 - Classificação de Nota
# Exercicio2: Conceito da nota
nota = float(input("Digite a nota do aluno (0 a 10): "))

if nota >= 9:
    print("Conceito A")
elif nota >= 7:
    print("Conceito B")
elif nota >= 5:
    print("Conceito C")
else:
    print("Conceito D")

# Atividade 3 - Acesso ao Cinema (AND)
# Lendo idade e se tem carteirinha
idade = int(input("Digite sua idade: "))
carteirinha_de_estudante = input("você tem carteirinha de estudante? (s/n): ")

# Precisa ter MAIS de 12 anos e ter a carteirinha
if idade >= 12 and carteirinha_de_estudante == "s" :
    print("Entrada permitida com meia-entrada!")
else:
    print("Entrada permitida somente com ingresso inteiro")

# Atividade 4 - Promoção (OR)
# Verificando se é vip e se a compra é maior q 100 reais
valor_de_compra= float(input("qual foi o valor da compra? (em reais): "))
cliente_vip= input("você é cliente vip? (s/n): ")


# Basta ser VIP OU ter cupom para ganhar desconto
if valor_de_compra >100 or cliente_vip == "s":
    print("Parabéns! Você ganhou FRETE GRÁTIS!")
else:
    print("você não tem direito ao frete gratis!")